
services:

  database:
    healthcheck:
      retries: 3
      timeout: 5s
    restart: always

  sqlite: # just a dummy container
    extends: database
    image: alpine
    command: sleep infinity # keep the container running
    healthcheck:
      test: ["CMD", "true"] # always return 0

  mysql:
    extends: database
    image: mysql:${DB_VERSION:-8.4}
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
    # volumes:
    #   - mysql_data:/var/lib/mysql

  mariadb:
    extends: mysql
    image: mariadb:${DB_VERSION:-11.7}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]

  pgsql:
    extends: database
    image: postgres:${DB_VERSION:-17.4}
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U test -d test'"]
    # volumes:
    #   - pgsql_data:/var/lib/postgresql/data

  sqlsrv:
    extends: database
    image: mcr.microsoft.com/mssql/server:${DB_VERSION:-2022}-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: MyS3cureP4ssw0rd
      DB_USER: test
      DB_NAME: test
    ports:
      - 1433:1433
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-U", "sa", "-P", "MyS3cureP4ssw0rd", "-Q", "SELECT 1"]
    # volumes:
    #   - sqlsrv_data:/var/opt/mssql
