
services:

  database:
    extends:
      file: ./docker-compose.databases.yml
      service: ${DB_ENGINE:-sqlite}

  php:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
      tags:
        - ${COMPOSE_PROJECT_NAME}-php-${PHP_VERSION}
    image: ${COMPOSE_PROJECT_NAME}-php-${PHP_VERSION}
    pull_policy: never
    command: sleep infinity # keep the container running
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app
      - ${COMPOSER_CACHE_DIR:-/.composer/cache}:/.composer/cache
