---
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: sqlout
      MYSQL_PASSWORD: lara
      MYSQL_USER: lara
    expose:
      - 3306
    image: mysql
    restart: always

  php-7.3:
    build:
      args:
        PHP_VERSION: '7.3'
    depends_on:
      - mysql

  php-7.4:
    build:
      args:
        PHP_VERSION: '7.4'
    depends_on:
      - mysql

  php-8.0:
    build:
      args:
        PHP_VERSION: '8.0'
    depends_on:
      - mysql

  php-8.1:
    build:
      args:
        PHP_VERSION: '8.1'
    depends_on:
      - mysql

  php-8.2:
    build:
      args:
        PHP_VERSION: '8.2'
    depends_on:
      - mysql

  php-8.3:
    build:
      args:
        PHP_VERSION: '8.3'
    depends_on:
      - mysql
