name: "Check coverage"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
      - main
    paths:
      - src/**
      - tests/**
      - phpunit.xml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -proot -e 'CREATE DATABASE test'
          mysql -uroot -proot -e "CREATE USER 'test'@'%' IDENTIFIED WITH mysql_native_password BY 'test'"
          mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'%'"
          mysql -uroot -proot -e "FLUSH PRIVILEGES"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: curl, zip, mbstring, pdo, pdo_mysql
          coverage: xdebug
      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction
      - name: Setup .env
        run: |
          sed -i -E "s/^DB_HOST=.*$/DB_HOST=127.0.0.1/g" .env.test
      - name: Enable PHPUnit coverage
        run: |
          sed -i "s/<\!--<coverage/<coverage/g" phpunit.xml
          sed -i "s/<\/coverage>-->/<\/coverage>/g" phpunit.xml
      - name: Execute tests
        run: vendor/bin/phpunit
      - name: Code coverage summary report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: cobertura.xml
          badge: true
          format: markdown
          fail_below_min: false
          output: both
      - name: Add PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Fail below 50%
        uses: themichaelhall/check-code-coverage@v2
        with:
          report: clover.xml
          required-percentage: 50
