name: "Check coverage"
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [master, main]
    paths:
      - src/**
      - tests/**
      - phpunit.xml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate-coverage:
    name: "Generate coverage"
    uses: michaelbaril/shared/.github/workflows/run-tests.yml@main
    with:
      with-coverage: true
  check-coverage:
    needs: generate-coverage
    uses: michaelbaril/shared/.github/workflows/check-coverage.yml@main
